ibm:
  mq:
    queue-manager: ${QM}
    channel: ${CHANNEL}
    conn-name: ${CONNECTION_NAME}
    user: ${USER}
    password: ${PASSWORD}
    
server: 
  port: 8080
  
logging: 
  level: 
    org.springframework: INFO
    com.example: INFO