ibm:
  mq:
    queue-manager: ${QM}
    channel: ${CHANNEL}
    conn-name: ${CONNECTION_NAME}
    user: ${USER}
    password: ${PASSWORD}
    application-name: ${APP_NAME}

app:
  mq:
   queue-name: ${QUEUE_NAME}
       
server: 
  port: 8080
  
logging: 
  level: 
    org.springframework: INFO
    com.example: INFO